### ISSUE TITLE
Add Amphibiaweb logo

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#156]
How about in top left corner of the persistent menubar?

**Comment by tigerhawkvok** [comment]
I'm sure this has come up before, but is there a real source image for the AWeb logo? 

The best I can find is : http://amphibiaweb.org/images/homepage_images/awlogomed.jpg

which is about 4-8x too small (a good logo for responsiveness should be at least 512x512px, and ideally 2048x2048px; also, in a lossless format like `png` or `svg`, rather than `jpg`).

**Comment by mkoo** [comment]
yes we've talked about this before... long story.
Anyway a bunch of PNGs are varying resolutions are here:
https://github.com/AmphibiaWeb/amphibian-disease-tracker/tree/gh-pages/assets/icons
