### ISSUE TITLE
minting arks to dataset 

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#55]
arks get assigned to uploaded datasets so more than one may be associated to a given project    

Project views should list datasets including ark, date uploaded, maybe include its record count and other summary stats.

Each record would have dataset ark added to it for  timestamp tracking of uploading

--------------------
copy/pasted email from 2016.03.04

>Hi Philip, Greg Jongsma is asking for an ark for the Gabon dataset again!
>So can you confirm a few things for me?
>- does he have a registered account?
>-do they have a Gabon project (I think David Blackburn filled it out)? If not (DB said he cannot view it any longer) should I ask him to recreate?
>- should Greg reupload the spreadsheet for an ark?
>
>To the latter point, I spoke briefly to Deck about project arks-- if we mint arks for expeditions (=our projects) then dataset arks will be hierarchically arranged in relation to a expedition and we can have 1:many (expedition:datasets) which is the structure we're seeking.
(http://fims.readthedocs.org/en/latest/amphibian_disease_example.html)

>So can you adjust to that? I can ask Blackburn and Greg to reenter data to the portal but only when we're stable. Can you give an estimate for them? Needless to say, this is a critical piece of the portal so we need to get this right.
>Thanks, MK

**Comment by tigerhawkvok** [comment]
Following up with the email here so we have a unified thread.

Are expeditions what we want? Seems that the expeditions don't resolve to a project URI:
http://biscicol.org/biocode-fims/rest/fims.wadl#idp752895712

>**form params**
>
>|  param  |  data type  |
>|-------------|--------------------|
>|  expeditionCode  |  string  |
>|  expeditionTitle  |  string  |
>|  projectId  |  int  |
>|  public  |  boolean  |

[The readTheDocs site seems to confirm this](https://fims.readthedocs.org/en/latest/amphibian_disease_example.html):

![image](https://cloud.githubusercontent.com/assets/165937/13541118/46438522-e20f-11e5-9da3-16409e9e65f4.png)


While `bcid`s [have the `webAddress` parameter](http://biscicol.org/biocode-fims/rest/fims.wadl#idp752895712) which acts as a redirect, it seems the same isn't true for expeditions?

I'm going to write up some of the dependent code anyway, but I think I'm going to add John Deck as a member of the repo so I can tag him easily when these sorts of questions come up.

**Comment by tigerhawkvok** [comment]
Pinging @jdeck88 on this issue.

**Comment by jdeck88** [comment]
When an expedition is created there are two steps:

1. create an expedition in the "expeditions" table.  This is done so future datasets can reference expeditions and be grouped together.
2. create a bcid in the bcids table with resourcetype = "Collection".  Right now, the default for expeditions is that webaddress is null here.

The fix really is to just add a webaddress argument to the expedition minter web service.   I think this was left off initially because i wanted expeditions to display metadata instead of data for loaded data in biscicol (going back to an argument about whether a "published" dataset should be mutable or not).  Let me know if you want to go this route and i can make an issue in the fims-commons code to add it (can you link github issues across repositories)?

**Comment by tigerhawkvok** [comment]
I think that makes sense -- providing the expedition ARK resolves to URL if a `webAddress` is specified, and otherwise maintains the current behaviour. It seems like the other way to approach this is to mint a BCID for one of our "projects" and group that by expedition, but then that's muddying up the datastructure.

That'd be very helpful!

And yes, you can link issues across repos, they even show up pretty-printed :-)

**Comment by jdeck88** [comment]
Ability to assign webaddress to expedition fixed in biocodellc/biocode-fims-commons#9 and deployed at biscicol.org/
updated REST description is at:
http://biscicol.org/biocode-fims/rest/fims.wadl#idp140295938197592

Closing issue since it seems to be addressed...Let me know otherwise (or create a new issue)

John
