### ISSUE TITLE
user getting kicked out of system during data parsing

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#93]
User report:
>I opened a new account with my siu.edu address. While this time I was initially able to start creating a new project, during the data parsing part I was again kicked out of the system. I was also getting strange messages (for example, that I'm not authorized to do such operation, etc). Further attempts to go back to the project dashboards mirrored what happened with my previous (gmail.com) account -- it sends me back to the login page. So, I still can't access the system and upload data.
>
>Thus -- I don't think the problem is with my account names not being properly validated?
>
>Another suggestion is to have some longer display time for the error messages when uploading spreadsheets. The messages appear for just a few seconds, if there are several messages it would be convenient to have them listed in a final message that can only be dismissed with a click.

**Comment by tigerhawkvok** [comment]
Alessandro's IP address was changing rapidly, so the system was booting him out when it appeared he'd changed devices/locations.

Changed the IP validation to [ignore the last decimal block](https://github.com/AmphibiaWeb/amphibian-disease-tracker/commit/31d2afe2f2d1e06ac62ffef26a5ec5320aad6a97).

Fixed with commits 

31d2afe2f2d1e06ac62ffef26a5ec5320aad6a97
6a7597ff44d760733868b3678c5f9322ff099fe0
486a0889a72b704ef96737ac900044eed780e382
